/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymatou_lib_TestEntry */

#ifndef _Included_com_ymatou_lib_TestEntry
#define _Included_com_ymatou_lib_TestEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymatou_lib_TestEntry
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ymatou_lib_TestEntry_getStrFromC
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
